# Generated by Django 5.2.1 on 2025-05-18 07:13

import django.db.models.deletion
import utils.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=128)),
                ('updated_by', models.CharField(max_length=128)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('deleted_dtm', models.DateTimeField(default=None, null=True)),
                ('user_id', models.CharField(default=utils.functions.get_uuid, max_length=64, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=128, null=True)),
                ('profile_photo', models.CharField(blank=True, max_length=512, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_users',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('email',), name='unique_email_active')],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'token',
            },
        ),
    ]
