# Generated by Django 5.2.1 on 2025-05-18 07:13

import utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=128)),
                ('updated_by', models.CharField(max_length=128)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('deleted_dtm', models.DateTimeField(default=None, null=True)),
                ('customer_id', models.CharField(default=utils.functions.get_uuid, max_length=36, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
